# Dockerfile.prod
FROM python:3.11

WORKDIR /app

COPY requirements.txt .

# Instalar solo lo necesario para producción
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Usar Gunicorn para producción
CMD ["gunicorn", "--bind", "0.0.0.0:8000", "mi_proyecto_django.wsgi:application"]
